spring.datasource.url=jdbc:postgresql://aws-1-eu-west-1.pooler.supabase.com:6543/postgres?prepareThreshold=0
spring.datasource.username=postgres.rrbuaptvkhbpnxibrkdm
spring.datasource.password=MtAgoAgoMtMsa

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

spring.datasource.hikari.data-source-properties.ssl=true
spring.datasource.hikari.data-source-properties.sslmode=require

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# File Upload Limits
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

supabase.url=https://rrbuaptvkhbpnxibrkdm.supabase.co
supabase.key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJyYnVhcHR2a2hicG54aWJya2RtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njc5NjM2OTMsImV4cCI6MjA4MzUzOTY5M30.WWH0w070nD3fLSv2aaxK6WhCO5KZrN4CEG7fFENS1b0
supabase.bucket=issue-images
