spring.datasource.url=jdbc:postgresql://db.rrbuaptvkhbpnxibrkdm.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=MtAgoAgoMtMsa

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

spring.datasource.hikari.data-source-properties.ssl=true
spring.datasource.hikari.data-source-properties.sslmode=require

spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

logging.level.org.springframework=DEBUG
